#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rtslib-fb
Version  : 2.1.62
Release  : 23
URL      : https://pypi.python.org/packages/24/d6/1b9b5ff514220db125e124b023f9be16686acd94e3dcf70608b5b338eb08/rtslib-fb-2.1.62.tar.gz
Source0  : https://pypi.python.org/packages/24/d6/1b9b5ff514220db125e124b023f9be16686acd94e3dcf70608b5b338eb08/rtslib-fb-2.1.62.tar.gz
Summary  : API for Linux kernel SCSI target (aka LIO)
Group    : Development/Tools
License  : Apache-2.0
Requires: rtslib-fb-bin
Requires: rtslib-fb-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
No detailed description available

%package bin
Summary: bin components for the rtslib-fb package.
Group: Binaries

%description bin
bin components for the rtslib-fb package.


%package python
Summary: python components for the rtslib-fb package.
Group: Default

%description python
python components for the rtslib-fb package.


%prep
%setup -q -n rtslib-fb-2.1.62

%build
export LANG=C
export SOURCE_DATE_EPOCH=1487790700
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1487790700
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/targetctl

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
